export enum EventKey {
  AppLaunched = 'AppLaunched',
  FireStoreError = 'FireStoreError',
  FireStoreSuccess = 'FireStoreSuccess',
  CreateRconFabClicked = 'CreateRconFabClicked',
  ScreenLoaded = 'ScreenLoaded',
  CreateRconScreenLoaded = 'CreateRconScreenLoaded',
  ServerFileOperationSuccess = 'ServerFileOperationSuccess',
  ServerFileOperationFailed = 'ServerFileOperationFailed',
  LocalFileOperationSuccess = 'LocalFileOperationSuccess',
  LocalFileOperationFailed = 'LocalFileOperationFailed',
  CreateProjectInteracted = 'CreateProjectInteracted',
  ViewProjectInteracted = 'ViewProjectInteracted',
  CreateProjectFadInteracted = 'CreateProjectFadInteracted',
  LocalStorageInValidRCON = 'LocalStorageInValidRCON',
  LocalStorageError = 'LocalStorageError',
}
